---
# This file is used by developers who use ./scripts/deploy.sh to set up a local
# development environment to help with development this module.
version: '3'

services:
  drupal:
    image: dummy_image_required
    volumes:
      - ".:/var/www/html/modules/custom/webhook_receiver"
    working_dir: /var/www/html

  webserver:
    build:
      context: .
      dockerfile: Dummy_Dockerfile_required
    ports:
      - "80"
    depends_on:
      - drupal

  mysql:
    image: mariadb
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'

# Specifying the network name makes it predictable on all environments,
# for example when we run browser tests.
# See https://github.com/docker/compose/issues/3736.
networks:
  default:
    external:
      name: webhook_receiver_default
