<?php

/**
 * @file
 * Runtime hooks.
 */

// @codingStandardsIgnoreStart
use Drupal\webhook_receiver\WebhookReceiver;
// @codingStandardsIgnoreEnd

/**
 * Quick access to the webhook_receiver service, useful for debugging.
 *
 * @return \Drupal\webhook_receiver\WebhookReceiver
 *   The WebhookReceiver service.
 */
// @codingStandardsIgnoreStart
// PHP Lint wants this to be prefixed with the module name, but it _is_
// the same as the module name, so I consider this ok.
function webhook_receiver() : WebhookReceiver {
// @codingStandardsIgnoreEnd
  return \Drupal::service('webhook_receiver');
}
